version: '3.9'

services:
  web:
    build: .
    container_name: quiz_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: quiz_db
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: quiz_redis
    ports:
      - "6379:6379"
